AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31
Description: >-
  b2b-smf_core

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 30
    Environment:
      Variables:
        APP_ID: e3804a193dc216170b8e4c306efd187f
        APP_SECRET: yerawiyizevu
        JWT_SECRET_KEY: !Ref JwtSecretKey
        JWT_REFRESH_SECRET_KEY: !Ref JwtRefreshSecretKey
        INTERNAL_CLIENT_ID: Dzynkraft
        INTERNAL_CLIENT_SECRET: Dzynkraft@65013
        INTERNAL_JWT_SECRET: smf#650rspvk
        TRACKING_TOKEN_SECRET: n8n#650rspvksdrfa
        INTERNAL_API_SECRET: vkrshpnhna!2854#$

Resources:
  B2BLeadsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: b2b-smf-core-Leads
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: phoneNumber
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: phoneNumber-index
          KeySchema:
            - AttributeName: phoneNumber
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1


  LeadLinkVisitsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: b2b-smf-core-LeadLinkVisits
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1


  SendEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/Form/sendEmail.handler
      Runtime: nodejs20.x
      Timeout: 20
      Role: arn:aws:iam::337909757009:role/b2b-smf-core-role
      Events:
        SendEmailApi:
          Type: Api
          Properties:
            Path: /form
            Method: post
            RestApiId: !Ref B2BSMFAPI

  SendOtpFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/Form/sendOtp.handler
      Runtime: nodejs20.x
      Timeout: 20
      Role: arn:aws:iam::337909757009:role/b2b-smf-core-role
      Events:
        SendOtpApi:
          Type: Api
          Properties:
            Path: /form/send-otp
            Method: post
            RestApiId: !Ref B2BSMFAPI

  VerifyOtpFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/Form/verifyOtp.handler
      Runtime: nodejs20.x
      Timeout: 30
      Role: arn:aws:iam::337909757009:role/b2b-smf-core-role
      Events:
        VerifyOtpApi:
          Type: Api
          Properties:
            Path: /form/verify-otp
            Method: post
            RestApiId: !Ref B2BSMFAPI

  DownloadReportFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/Form/downloadReport.handler
      Runtime: nodejs20.x
      Timeout: 20
      Role: arn:aws:iam::337909757009:role/b2b-smf-core-role
      Events:
        DownloadReportApi:
          Type: Api
          Properties:
            Path: /form/download-report
            Method: post
            RestApiId: !Ref B2BSMFAPI

  SaveLeadOnAutoFillFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/Form/saveLeadOnAutoFill.handler
      Runtime: nodejs20.x
      Timeout: 20
      Role: arn:aws:iam::337909757009:role/b2b-smf-core-role
      Events:
        SaveLeadOnAutoFillApi:
          Type: Api
          Properties:
            Path: /form/auto-lead
            Method: post
            RestApiId: !Ref B2BSMFAPI

  # CreateTokeForCallingTrackingLinkFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     Handler: src/n8n/generateInternalJWT.handler
  #     Runtime: nodejs20.x
  #     Timeout: 20
  #     Role: arn:aws:iam::337909757009:role/b2b-smf-core-role
  #     Events:
  #       CreateTokeForCallingTrackingLinkApi:
  #         Type: Api
  #         Properties:
  #           Path: /internal/auth/token
  #           Method: post
  #           RestApiId: !Ref B2BSMFAPI

  GenerateLinkForTrackingLinkFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/n8n/generateTrackingLink.handler
      Runtime: nodejs20.x
      Timeout: 20
      Role: arn:aws:iam::337909757009:role/b2b-smf-core-role
      Events:
        generateTrackingLinkApi:
          Type: Api
          Properties:
            Path: /redirect-link
            Method: post
            RestApiId: !Ref B2BSMFAPI

  # GetEmailFromTokenFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     Handler: src/n8n/decryptTheEmail.handler
  #     Runtime: nodejs20.x
  #     Timeout: 20
  #     Role: arn:aws:iam::337909757009:role/b2b-smf-core-role
  #     Events:
  #       GetEmailFromTokenApi:
  #         Type: Api
  #         Properties:
  #           Path: /get-email
  #           Method: get
  #           RestApiId: !Ref B2BSMFAPI

  TrackUserVisitFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/n8n/trackVisit.handler
      Runtime: nodejs20.x
      Timeout: 20
      Role: arn:aws:iam::337909757009:role/b2b-smf-core-role
      Events:
        TrackUserVisitApi:
          Type: Api
          Properties:
            Path: /track-visit
            Method: post
            RestApiId: !Ref B2BSMFAPI

  

  B2BSMFAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'https://b2b.showmyflat.com'"
        AllowCredentials: true
      EndpointConfiguration: REGIONAL

Parameters:
  JwtSecretKey:
    Type: String
    Description: Secret key for signing JWT tokens
    Default: b2b-smf#core-jwt%secretKey@3453
  JwtRefreshSecretKey:
    Type: String
    Description: Secret key for signing JWT refresh tokens
    Default: b2b!smf$core(jwt$refresh%secretKey)6789
